yolov7
acetrace/golf-trajectory pull request #3
Opened 2022-12-11 20:44 UTC by ACE-777

Tracking algorithm based on YoloV7 detection method in ```tracking_YOLO_V7```.
All files useful for yolov7 are in directories ```models``` and ```utils```.
The weights are in ```yolov7.pt```.

2022-12-13 14:53 UTC, evekeen commented on tracking_YOLO_V7.py
> +            # if ball_size > last_ball_size * size_factor or ball_size < last_ball_size / size_factor:
also why not?

2022-12-13 14:53 UTC, evekeen commented on tracking_YOLO_V7.py
> +    # im_data = Variable(im_data, volatile=True)
please remove commented code

2022-12-13 14:56 UTC, evekeen commented on tracking_YOLO_V7.py
> +    # Convert nx4 boxes from [x, y, w, h] to [x1, y1, x2, y2] where xy1=top-left, xy2=bottom-right
is original `x,y` a center? in this case, let's make it clear

2022-12-13 14:56 UTC, evekeen commented on tracking_YOLO_V7.py
> +def xywh2xyxy(x):
```suggestion
def xywh2xyxy(box):
```

2022-12-13 14:58 UTC, evekeen commented on tracking_YOLO_V7.py
> +class Ensemble(nn.ModuleList):
so did you copy these classes to delete extra files? I still see these classes in yolov7 files

2022-12-13 18:19 UTC, ACE-777 commented on tracking_YOLO_V7.py
> +            # if ball_size > last_ball_size * size_factor or ball_size < last_ball_size / size_factor:
Add

2022-12-13 18:37 UTC, ACE-777 commented on tracking_YOLO_V7.py
> +    # im_data = Variable(im_data, volatile=True)
Left only useable for video

2022-12-13 20:10 UTC, ACE-777 commented
Tracking algorithm based on YoloV7 detection method in ```tracking_YOLO_V7```.
The weights are in ```yolov7.pt```.

2022-12-13 20:10 UTC, evekeen commented on tracking_YOLO_V7.py
> +class Ensemble(nn.ModuleList):
still here?

2022-12-13 22:23 UTC, ACE-777 commented on tracking_YOLO_V7.py
> +class Ensemble(nn.ModuleList):
remove experimental.py

2022-12-14 19:51 UTC, ACE-777 commented
For testing algorihtm use next sceme of directories: 
```
golf-trajectory (git project)
+--prob_data_1
+-----Golf_1
+-----Golf_2
+-----Golf_4
+-----Golf_5
+-----Golf_8
+-----Golf_10
+-----Golf_16
+-----Golf_17
+--prob_annotations
+-----01_001.xml
+----- ...
+--tracking_YOLO_V7.py
+-- ...
```
Algorithm calculates a metric IoU for every image from each directory of prob_data_1. Then, it calculates the average value of the metric IoU for all received results and visualizes in console. For examlpe:
 ```average iou for all warmup videos 54.139223943154015%```.

2022-12-15 16:11 UTC, ACE-777 commented
Path to dir ```stabil_11_14``` with datasets is defined in a variable ```path_to_datasets_for_warmup```.
To save the original images, create a folder with the name ```save_full_image``` and specify the path in variable ```save_dir_for_full_img```.

The result of the average value of the metric over all datasets, including the first image for each dataset:
--image fragment size for detection 500X500: ```average iou for all warmup videos 13.244572383634485%```;
--image fragment size for detection 600X600: ```average iou for all warmup videos 15.477244443488573%```.

The result of the average value of the metric over all datasets, without the first image for each dataset:
--image fragment size for detection 600X600: ```average iou for all warmup videos 13.435528622377637%```.

2022-12-16 15:44 UTC, evekeen commented on tracking_YOLO_V7.py
> +            imglist = os.listdir(path_to_datasets_for_warmup + r"\\" + dir_of_videos_list[dir_name])  # opt.source
no backslashes please - use `os.path.join()`

2022-12-16 15:44 UTC, evekeen commented on tracking_YOLO_V7.py
> +            # if video_path == "":
remove ALL the commented code, please

2022-12-16 15:45 UTC, evekeen commented on tracking_YOLO_V7.py
> +                    out_path = "Golf Ball/Golf Ball"
no need for that, but if you want to, please accept path as an optional cmd argument

2022-12-16 15:45 UTC, evekeen commented on tracking_YOLO_V7.py
> +            save_dir_for_full_img = "C:\\Users\\misha\\golfTrajectory\\golftrajectory\\save_full_image"
cmd argument

2022-12-16 15:48 UTC, evekeen commented on tracking_YOLO_V7.py
> +    print("average iou for all warmup videos {}%".format(average_iou * 100))
```suggestion
    print("average iou for all warmup videos {0:.0f}%".format(average_iou * 100))
```

2022-12-17 19:09 UTC, ACE-777 commented on tracking_YOLO_V7.py
> +                    out_path = "Golf Ball/Golf Ball"
deleted!

2022-12-17 19:10 UTC, ACE-777 commented on tracking_YOLO_V7.py
> +            # if video_path == "":
done here!

2022-12-17 19:10 UTC, ACE-777 commented on tracking_YOLO_V7.py
> +                classes = 32, 1  # sports ball, bicycle
deleted!

2022-12-17 19:12 UTC, ACE-777 commented on tracking_YOLO_V7.py
> +    print("average iou for all warmup videos {}%".format(average_iou * 100))
done!

2022-12-17 19:29 UTC, ACE-777 commented on tracking_YOLO_V7.py
> +            imglist = os.listdir(path_to_datasets_for_warmup + r"\\" + dir_of_videos_list[dir_name])  # opt.source
done!

2022-12-27 15:14 UTC, evekeen commented on tracking_YOLO_V7.py
> +                      default="C:\\Users\\misha\\golfTrajectory\\stabil_11_14\\stabil_11_14\\")
let's remove these default paths

2022-12-27 15:16 UTC, evekeen commented on tracking_YOLO_V7.py
> +    im_data = im_data.cuda()
please, no CUDA for inference

2022-12-27 15:23 UTC, evekeen commented on tracking_YOLO_V7.py
> +                                im_file_save = os.path.join(path_to_datasets_for_warmup, os.path.join(dir_of_videos_list[dir_name],
please, don't write into dataset

2022-12-27 15:27 UTC, evekeen commented on tracking_YOLO_V7.py
> +            source, weights, imgsz = 'sub_im.jpg', 'yolov7.pt', 600  # image_size
```suggestion
            source, weights, imgsz = 'sub_im.jpg', 'yolov7.pt', 640  # image_size
```

2022-12-27 15:27 UTC, evekeen requested changes
please fix according to comments and apply changes from my PR first

2022-12-28 11:04 UTC, ACE-777 commented on tracking_YOLO_V7.py
> +                      default="C:\\Users\\misha\\golfTrajectory\\stabil_11_14\\stabil_11_14\\")
done!

2022-12-28 11:05 UTC, ACE-777 commented on tracking_YOLO_V7.py
> +    im_data = im_data.cuda()
remove cuda

2022-12-28 11:15 UTC, ACE-777 commented on tracking_YOLO_V7.py
> +                                im_file_save = os.path.join(path_to_datasets_for_warmup, os.path.join(dir_of_videos_list[dir_name],
I write in ```save_full_image```. This dir doesn't connect with dataset:https://github.com/acetrace/golf-trajectory/blob/a8f1825516dbc67d86ba82953bf3c3b3eed07baa/tracking_YOLO_V7.py#L1126

2022-12-28 11:16 UTC, ACE-777 commented on tracking_YOLO_V7.py
> +            source, weights, imgsz = 'sub_im.jpg', 'yolov7.pt', 600  # image_size
Done!

2022-12-28 15:53 UTC, evekeen commented on tracking_YOLO_V7.py
> +                                im_file_save = os.path.join(path_to_datasets_for_warmup, os.path.join(dir_of_videos_list[dir_name],
it has `seq_path` in it, so it must be in the dataset

2022-12-28 15:56 UTC, evekeen commented on tracking_YOLO_V7.py
> +                                    im_file_save = os.path.join(seq_path, imglist[num_of_processed_images_old])
rename `im_file_save` please

2022-12-28 15:58 UTC, evekeen requested changes
```
  File "/Users/ivkin/my/golf-trajectory/tracking_YOLO_V7.py", line 1013, in <module>
    im = im_in[:, :, ::-1]  # go throw the end to begin for each number
IndexError: too many indices for array: array is 0-dimensional, but 3 were indexed
```

2022-12-28 16:06 UTC, ACE-777 commented
> ```
>   File "/Users/ivkin/my/golf-trajectory/tracking_YOLO_V7.py", line 1013, in <module>
>     im = im_in[:, :, ::-1]  # go throw the end to begin for each number
> IndexError: too many indices for array: array is 0-dimensional, but 3 were indexed
> ```
Maybe its connected with im_file from datasets, that are located in that way: ```C:\\Users\\misha\\golfTrajectory\\stabil_11_14\\stabil_11_14\\0ewv4ibe2ce2zn58ti5yu65wzkm2-img_8209-17.27.mov\00000001.jpg```

https://github.com/acetrace/golf-trajectory/blob/4b2768e2fe943d142c7819097729117272113d74/tracking_YOLO_V7.py#L1006-L1007

2022-12-28 16:46 UTC, evekeen commented
> > ```
> >   File "/Users/ivkin/my/golf-trajectory/tracking_YOLO_V7.py", line 1013, in <module>
> >     im = im_in[:, :, ::-1]  # go throw the end to begin for each number
> > IndexError: too many indices for array: array is 0-dimensional, but 3 were indexed
> > ```
> 
> Maybe its connected with im_file from datasets, that are located in that way: `C:\\Users\\misha\\golfTrajectory\\stabil_11_14\\stabil_11_14\\0ewv4ibe2ce2zn58ti5yu65wzkm2-img_8209-17.27.mov\00000001.jpg`
> 
> https://github.com/acetrace/golf-trajectory/blob/4b2768e2fe943d142c7819097729117272113d74/tracking_YOLO_V7.py#L1006-L1007

no, it's something else

2023-01-04 09:34 UTC, ACE-777 commented
Fixed IndexError. Works with a non-img file in the video directory.

2023-01-04 09:35 UTC, ACE-777 commented
> > > ```
> > >   File "/Users/ivkin/my/golf-trajectory/tracking_YOLO_V7.py", line 1013, in <module>
> > >     im = im_in[:, :, ::-1]  # go throw the end to begin for each number
> > > IndexError: too many indices for array: array is 0-dimensional, but 3 were indexed
> > > ```
> > 
> > 
> > Maybe its connected with im_file from datasets, that are located in that way: `C:\\Users\\misha\\golfTrajectory\\stabil_11_14\\stabil_11_14\\0ewv4ibe2ce2zn58ti5yu65wzkm2-img_8209-17.27.mov\00000001.jpg`
> > https://github.com/acetrace/golf-trajectory/blob/4b2768e2fe943d142c7819097729117272113d74/tracking_YOLO_V7.py#L1006-L1007
> 
> no, it's something else

Fixed IndexError. Works with a non-img file in the video directory.

2023-01-04 16:13 UTC, evekeen approved these changes

2023-01-04 16:13 UTC, merged